### ISSUE TITLE
Should butcher be an optional dependency?

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/vetiver-r#24]
i.e. it is only used for butchering the lm object here
https://github.com/tidymodels/vetiver/blob/579a5425db2c6ad9e8668d3edcaaaea47a12086d/R/vetiver-model.R#L76

and for a few tests.

---

I wonder if butchering should be optional in general? Like, you could add a `butcher = TRUE` argument here to the lm method (but not to the generic function):
https://github.com/tidymodels/vetiver/blob/579a5425db2c6ad9e8668d3edcaaaea47a12086d/R/vetiver-model.R#L69

You could Suggest butcher, and if `butcher = TRUE` it would check that butcher is installed before trying to butcher.

---

I mainly mention this because there might be certain recipes or parsnip models where we don't want to try and butcher the model. I think there are a few edge cases where butchering unfortunately breaks some things, but I can't remember exactly what those are.

**Comment by juliasilge** [comment]
We are using butcher pretty extensively for deployed model objects, so I think it makes sense to keep in Imports. 👍
